### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/nlp/query

Pokaż top 10 sklepów

###
POST http://localhost:8080/nlp/

###
POST http://localhost:8080/nlp/query
Content-Type: text/plain

pokaz najlepsze 10 sklepow pod wzgledem sprzedazy w dni siwateczne